In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 13 ms, sys: 4.54 ms, total: 17.5 ms
Wall time: 16.2 ms


In [5]:
time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 534 ms, sys: 122 ms, total: 655 ms
Wall time: 654 ms


In [8]:
data = np.random.randn(2, 3)

In [9]:
data

array([[-0.36846458,  1.4854728 , -0.35586379],
       [ 0.86963274,  0.28043684, -0.7737697 ]])

In [10]:
data * 10

array([[-3.6846458 , 14.854728  , -3.55863792],
       [ 8.69632744,  2.8043684 , -7.73769705]])

In [11]:
data

array([[-0.36846458,  1.4854728 , -0.35586379],
       [ 0.86963274,  0.28043684, -0.7737697 ]])

In [12]:
data + data

array([[-0.73692916,  2.9709456 , -0.71172758],
       [ 1.73926549,  0.56087368, -1.54753941]])

In [13]:
data.shape

(2, 3)

In [14]:
data.dtype

dtype('float64')

In [16]:
# Creating array
data1 = [6, 7.5, 8, 0, 1]

In [17]:
arr1 = np.array(data1)

In [18]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [19]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [20]:
arr2 = np.array(data2)

In [21]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
arr2.ndim

2

In [23]:
arr2.shape

(2, 4)

In [24]:
arr1.dtype

dtype('float64')

In [25]:
arr2.dtype

dtype('int64')

In [26]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
np.empty((2,3,2))

array([[[ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000, -2.68156159e+154],
        [-2.68156159e+154, -4.33884788e-311]]])

In [31]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [33]:
arr1

array([1., 2., 3.])

In [34]:
arr1.dtype

dtype('float64')

In [35]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [36]:
arr2

array([1, 2, 3], dtype=int32)

In [37]:
arr2.dtype

dtype('int32')

In [38]:
arr = np.array([1,2,3,4,5])

In [39]:
arr.dtype

dtype('int64')

In [40]:
float_arr = arr.astype(np.float64)

In [41]:
float_arr

array([1., 2., 3., 4., 5.])

In [42]:
float_arr.dtype

dtype('float64')

In [43]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [44]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [45]:
# Use another array's dtype
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [47]:
# Arithmetic with NumPy Arrays
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [48]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [49]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [50]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [52]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [53]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [54]:
arr2 = np.array([[0., 4. , 1.],[7., 2., 12.]])

In [55]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [56]:
arr2 > arr1

array([[False,  True, False],
       [ True, False,  True]])

In [57]:
arr = arr2 > arr1

In [58]:
arr

array([[False,  True, False],
       [ True, False,  True]])

In [59]:
arr.dtype

dtype('bool')

In [60]:
# Indexing and Slicing
arr = np.arange(10)

In [61]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr[5]

5

In [63]:
arr[5:8]

array([5, 6, 7])

In [64]:
arr[5:8] = 12

In [65]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [66]:
arr_slice = arr[5:8]

In [67]:
arr_slice

array([12, 12, 12])

In [68]:
arr_slice[1] = 12345

In [69]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [70]:
arr_slice[:] = 64

In [71]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [73]:
# 2d
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [74]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
arr2d[2]

array([7, 8, 9])

In [76]:
arr2d[0][2]

3

In [77]:
arr2d[0, 2]

3